"""
Overview router — GET /api/overview

Returns high-risk user count, pending case count, batch prediction status,
risk score histogram, and top high-risk pending user list.
"""
from __future__ import annotations

import logging
from typing import List, Optional

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from backend.app.services.case_service import CaseService
from backend.app.services.model_service import ModelService

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api")

# ---------------------------------------------------------------------------
# Global batch state — set to True after a successful batch prediction run
# ---------------------------------------------------------------------------
_batch_executed: bool = False
_batch_results: List = []  # cached PredictionResult list from last batch run


def set_batch_results(results: list) -> None:
    """Called by predict router after a successful batch prediction."""
    global _batch_executed, _batch_results
    _batch_executed = True
    _batch_results = results


def get_batch_results() -> list:
    """Return the cached batch prediction results."""
    return _batch_results


# ---------------------------------------------------------------------------
# Response schemas
# ---------------------------------------------------------------------------


class HistogramBin(BaseModel):
    bin: str    # e.g. "0.0-0.1"
    count: int


class HighRiskPendingItem(BaseModel):
    user_id: str
    risk_score: float
    risk_level: str
    fraud_label: Optional[int] = None  # 1=fraud, 0=normal, null=unknown


class OverviewResponse(BaseModel):
    total_users: int
    fraud_count: int
    normal_count: int
    high_risk_count: int
    risk_histogram: List[HistogramBin]
    high_risk_list: List[HighRiskPendingItem]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_HIGH_RISK_THRESHOLD = 0.35

# Histogram bin edges: 10 bins from 0.0 to 1.0
_BIN_LABELS = [f"{i/10:.1f}-{(i+1)/10:.1f}" for i in range(10)]


def _build_histogram(scores: List[float]) -> List[HistogramBin]:
    """Bucket risk scores into 10 equal-width bins [0.0-0.1, ..., 0.9-1.0]."""
    counts = [0] * 10
    for score in scores:
        # Clamp to [0, 1] and compute bin index
        idx = min(int(score * 10), 9)
        counts[idx] += 1
    return [HistogramBin(bin=label, count=cnt) for label, cnt in zip(_BIN_LABELS, counts)]


# ---------------------------------------------------------------------------
# Endpoint
# ---------------------------------------------------------------------------


@router.get("/overview", response_model=OverviewResponse)
def get_overview() -> OverviewResponse:
    """
    Return dashboard overview from pre-computed JSON file.
    Generated by scripts/compute_overview.py.
    """
    import json as _json
    from pathlib import Path

    overview_path = Path(__file__).resolve().parents[3] / "outputs" / "overview.json"

    if not overview_path.exists():
        raise HTTPException(
            status_code=500,
            detail="overview.json not found. Run: uv run python scripts/compute_overview.py",
        )

    with open(overview_path, "r", encoding="utf-8") as f:
        data = _json.load(f)

    return OverviewResponse(**data)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _get_pending_case_count() -> int:
    """Return the number of cases with status == 'pending'."""
    try:
        case_service = CaseService.get_instance()
        all_cases = case_service.get_all_cases()
        return sum(1 for c in all_cases if c.status == "pending")
    except Exception as exc:  # noqa: BLE001
        logger.warning("Failed to fetch pending case count: %s", exc)
        return 0


def _get_case_status_map() -> dict:
    """Return a dict mapping user_id -> case status."""
    try:
        case_service = CaseService.get_instance()
        all_cases = case_service.get_all_cases()
        return {c.user_id: c.status for c in all_cases}
    except Exception as exc:  # noqa: BLE001
        logger.warning("Failed to fetch case status map: %s", exc)
        return {}
